### ISSUE TITLE
[Bug] sendable 관련 로직 오류

### ISSUE THREAD

**Issue by onsuk** [Devrother/ironmental-send-contents#20]
## Description
- 다음과 같은 에러 로그 재발생
- 그로 인해 AWS lambda의 실행이 멈추었고, 10/28(월)에 콘텐츠 발송이 되지 않음
- 존재하지 않는 interview object id가 `sendable` 변수에 할당될 경우 발생하는 것으로 확인

### Error
```
{
    "errorMessage": "Cannot destructure property `question` of 'undefined' or 'null'.",
    "errorType": "TypeError",
    "stackTrace": [
        "keywords (/var/task/src/webpack:/src/cron.js:74:5)",
        "<anonymous>",
        "process._tickDomainCallback (internal/process/next_tick.js:228:7)"
    ]
}
```

### Expected behaviour
- 존재하지 않는 object id가 왜 `sendable`로 전달되는지 관련로직 검토 필요
- 혹은 다른 이유 때문인지 검토 필요

**Comment by SeungUkLee** [comment]
DB에 Tags에 있는 interviews id가 Interviews 에는 없어서 발생하는 것으로 확인.

**Comment by onsuk** [comment]
`tags` 콜렉션의 `interviews` 필드의 값 중 `interviews` 콜렉션에 없는 값 삭제
